#!/usr/bin/env bash

# test config
writers=2
run_seconds=1
write_delay=5
output_type=file
output_path=srclogs
output_arg=
fluent_out_path=outlogs
fluent_db_path=pos

# log writers output to $output_path
if [ "$output_type" == "file" ]; then
  if [ ! -d $output_path ]; then
    mkdir $output_path
    chmod 777 $output_path
  elif [ ! -z "$(ls -A $output_path)" ]; then
    rm $output_path/*
  fi
  output_arg="-o $output_type -p $output_path"
else
  output_arg="-o $output_type"
fi

# fluentd outputs to $fluent_out_path
if [ ! -d $fluent_out_path ]; then
  mkdir $fluent_out_path
  chmod 777 $fluent_out_path
elif [ ! -z "$(ls -A $fluent_out_path)" ]; then
  rm $fluent_out_path/*
fi

# fluentd uses this $fluent_db_path for the file position
if [ ! -d $fluent_db_path ]; then
  mkdir $fluent_db_path
  chmod 777 $fluent_db_path
elif [ ! -z "$(ls -A $fluent_db_path)" ]; then
  rm $fluent_db_path/*
fi

docker-compose up

#python3 bin/test_runner.py -n $writers -r $run_seconds -w $write_delay $output_arg
