{
 "title": "Fluentd resource usage",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Fluentd CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"fluentd\"}[30s]))*100",
     "legendFormat": "%CPU "
    }
   ]
  },
  {
   "title": "Fluentd logs output",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fluentd_output_status_emit_count",
     "legendFormat": "log count"
    }
   ]
  },
  {
   "title": "Fluentd memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"fluentd\"}",
     "legendFormat": "Memory use (bytes)"
    }
   ]
  },
  {
   "title": "Fluentd logs/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(fluentd_output_status_emit_count[30s])",
     "legendFormat": "logs/s"
    }
   ]
  }
 ]
}