scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080
- job_name: fluentd
  scrape_interval: 5s
  static_configs:
  - targets:
    - fluentd:8000
